name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker images with Docker Compose
        run: docker compose -f docker-compose.yml build

      - name: Push Docker images with Docker Compose
        run: docker compose -f docker-compose.yml push

      - name: Run tests
        run: |
          docker compose -f docker-compose.yml up -d
          docker compose -f docker-compose.yml run test

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /home/user/microservices-app
            git pull origin main
            docker compose down
            docker compose pull
            docker compose up -d
